species_primary = {
    "Verdant": ["VERDANT :",
                " This ",
                " Plant ",
                " Is",
                " Happy"],
    "Azure": [""],
    "Blizzard": [""],
    "Crimson": ["CRIMSON:",
                "omegalul"],
    "Crystalline": ["CRYSTALLINE:",
                    "beans"],
    "Celestial": [""],
    "Deadly": [""],
    "Decaying": [""],
    "Dirty": [""],
    "Endothermic": [""],
    "Exothermic": [""],
    "Explosive": [""],
    "Eternal": [""],
    "Hollow": [""],
    "Hasted": [""],
    "Lunar": [""],
    "Magmatic": [""],
    "Metal": [""],
    "Necrotic": [""],
    "Nocturnal": [""],
    "Programmed": ["yes"],
    "Rocky": [""],
    "Radioactive": [""],
    "Solar": [""],
    "Steel": [""],
    "Temporal": [""],
    "Tectonic": [""],
    "Titanium": [""],
    "Unstable": [""],
    "Vital": [""],
}
species_secondary = {
    "Verdant": ["ooooooooooooooooooooooooooo"],
    "Azure": [""],
    "Blizzard": [""],
    "Crimson": ["CRIMSON:",
                "omegalul"],
    "Crystalline": ["CRYSTALLINE:",
                    "beans"],
    "Celestial": [""],
    "Deadly": [""],
    "Decaying": [""],
    "Dirty": [""],
    "Endothermic": [""],
    "Exothermic": [""],
    "Explosive": [""],
    "Eternal": [""],
    "Hollow": [""],
    "Hasted": [""],
    "Lunar": [""],
    "Magmatic": [""],
    "Metal": [""],
    "Necrotic": [""],
    "Nocturnal": [""],
    "Programmed": ["yes"],
    "Rocky": [""],
    "Radioactive": [""],
    "Solar": [""],
    "Steel": [""],
    "Temporal": [""],
    "Tectonic": [""],
    "Titanium": [""],
    "Unstable": [""],
    "Vital": [""],
}
