from Garden.Plants.plantType import PlantType
from useful_functions import *

plant_species = {
    "Verdant": PlantType(
        type_name="Verdant",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=[1, 1],
        base_yield=[350, 50],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        mutation_recipe=[None],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "------------------------------"]
    ),
    "Azure": PlantType(
        type_name="Azure",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=[1, 1],
        base_yield=[50, 50],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[2, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        mutation_recipe=["Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Radioactive", "Endothermic"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "------------------------------"]
    ),
    "Blizzard": PlantType(
        type_name="Blizzard",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=[1, 1],
        base_yield=[50, 50],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        mutation_recipe=["Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "------------------------------"]
    ),
    "Crimson": PlantType(
        type_name="Crimson",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=[1, 1],
        base_yield=[50, 50],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        mutation_recipe=["Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "------------------------------"]
    ),
    "Crystalline": PlantType(
        type_name="Crystalline",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=[1, 1],
        base_yield=[50, 50],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        mutation_recipe=["Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "------------------------------"]
    ),
    "Celestial": PlantType(
        type_name="Celestial",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=[1, 1],
        base_yield=[50, 50],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        mutation_recipe=["Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "------------------------------"]
    ),
    "Deadly": PlantType(
        type_name="Deadly",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=[1, 1],
        base_yield=[50, 50],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        mutation_recipe=["Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "------------------------------"]
    ),
    "Decaying": PlantType(
        type_name="Decaying",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=[1, 1],
        base_yield=[50, 50],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        mutation_recipe=["Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "------------------------------"]
    ),
    "Dirty": PlantType(
        type_name="Dirty",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=[1, 1],
        base_yield=[50, 50],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        mutation_recipe=["Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "------------------------------"]
    ),
    "Endothermic": PlantType(
        type_name="Endothermic",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=[1, 1],
        base_yield=[50, 50],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        mutation_recipe=["Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "------------------------------"]
    ),
    "Exothermic": PlantType(
        type_name="Exothermic",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=[1, 1],
        base_yield=[50, 50],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        mutation_recipe=["Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "------------------------------"]
    ),
    "Explosive": PlantType(
        type_name="Explosive",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=[1, 1],
        base_yield=[50, 50],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        mutation_recipe=["Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "------------------------------"]
    ),
    "Eternal": PlantType(
        type_name="Eternal",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=[1, 1],
        base_yield=[50, 50],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        mutation_recipe=["Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "------------------------------"]
    ),
    "Hollow": PlantType(
        type_name="Hollow",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=[1, 1],
        base_yield=[50, 50],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        mutation_recipe=["Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "------------------------------"]
    ),
    "Hasted": PlantType(
        type_name="Hasted",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=[1, 1],
        base_yield=[50, 50],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        mutation_recipe=["Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "------------------------------"]
    ),
    "Lunar": PlantType(
        type_name="Lunar",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=[1, 1],
        base_yield=[50, 50],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        mutation_recipe=["Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "------------------------------"]
    ),
    "Magmatic": PlantType(
        type_name="Magmatic",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=[1, 1],
        base_yield=[50, 50],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        mutation_recipe=["Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "------------------------------"]
    ),
    "Metallic": PlantType(
        type_name="Metallic",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=[1, 1],
        base_yield=[50, 50],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        mutation_recipe=["Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "------------------------------"]
    ),
    "Necrotic": PlantType(
        type_name="Necrotic",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=[1, 1],
        base_yield=[50, 50],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        mutation_recipe=["Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "------------------------------"]
    ),
    "Nocturnal": PlantType(
        type_name="Nocturnal",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=[1, 1],
        base_yield=[50, 50],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        mutation_recipe=["Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "------------------------------"]
    ),
    "Programmed": PlantType(
        type_name="Programmed",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=[1, 1],
        base_yield=[50, 50],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        mutation_recipe=["Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "------------------------------"]
    ),
    "Rocky": PlantType(
        type_name="Rocky",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=[1, 1],
        base_yield=[50, 50],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        mutation_recipe=["Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "------------------------------"]
    ),
    "Radioactive": PlantType(
        type_name="Radioactive",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=[1, 1],
        base_yield=[50, 50],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        mutation_recipe=["Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "------------------------------"]
    ),
    "Solar": PlantType(
        type_name="Solar",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=[1, 1],
        base_yield=[50, 50],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        mutation_recipe=["Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "------------------------------"]
    ),
    "Steel": PlantType(
        type_name="Steel",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=[1, 1],
        base_yield=[50, 50],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        mutation_recipe=["Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "------------------------------"]
    ),
    "Temporal": PlantType(
        type_name="Temporal",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=[1, 1],
        base_yield=[50, 50],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        mutation_recipe=["Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "------------------------------"]
    ),
    "Tectonic": PlantType(
        type_name="Tectonic",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=[1, 1],
        base_yield=[50, 50],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        mutation_recipe=["Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "------------------------------"]
    ),
    "Titanium": PlantType(
        type_name="Titanium",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=[1, 1],
        base_yield=[50, 50],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        mutation_recipe=["Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "------------------------------"]
    ),
    "Unstable": PlantType(
        type_name="Unstable",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=[1, 1],
        base_yield=[50, 50],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        mutation_recipe=["Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "------------------------------"]
    ),
    "Vital": PlantType(
        type_name="Vital",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=[1, 1],
        base_yield=[50, 50],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        mutation_recipe=["Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant", "Verdant"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "------------------------------"]
    ),
}
