from Garden.Plants.plantType import PlantType
from useful_functions import *

# [Primary stat, Secondary stat]


plant_species = {
    "Verdant": PlantType(
        type_name="Verdant",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1.11111,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=0,
        mutation_recipe=[None],
        colour=LIME_GREEN,
        is_unlocked=True,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Azure": PlantType(
        type_name="Azure",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=0,
        mutation_recipe=[None],
        colour=GREEN,
        is_unlocked=True,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Vermilion": PlantType(
        type_name="Vermilion",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=0,
        mutation_recipe=[None],
        colour=GREEN,
        is_unlocked=True,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Pale": PlantType(
        type_name="Pale",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=0,
        mutation_recipe=[None],
        colour=GREEN,
        is_unlocked=True,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Inked": PlantType(
        type_name="Inked",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=0,
        mutation_recipe=[None],
        colour=GREEN,
        is_unlocked=True,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Crimson": PlantType(
        type_name="Crimson",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=1,
        mutation_recipe=["Vermilion", "Vermilion", "Vermilion", "Vermilion"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Frosty": PlantType(
        type_name="Frosty",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=1,
        mutation_recipe=["Azure", "Azure", "Pale"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Heated": PlantType(
        type_name="Heated",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=1,
        mutation_recipe=["Vermilion", "Vermilion", "Inked"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Dirty": PlantType(
        type_name="Dirty",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=50,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=1,
        mutation_recipe=["Verdant", "Verdant", "Verdant", "Verdant"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Aquatic": PlantType(
        type_name="Aquatic",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=1,
        mutation_recipe=["Azure [Max]", "Azure [Max]", "Azure [Max]", "Azure [Max]"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Inverted": PlantType(
        type_name="Inverted",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=1,
        mutation_recipe=["Azure [Max]", "Azure [Max]", "Azure [Max]", "Azure [Max]"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Spectrum": PlantType(
        type_name="Spectrum",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=1,
        mutation_recipe=["Azure [Max]", "Azure [Max]", "Azure [Max]", "Azure [Max]"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Deadly": PlantType(
        type_name="Deadly",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=2,
        mutation_recipe=["Azure [Max]", "Azure [Max]", "Azure [Max]", "Azure [Max]"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Rocky": PlantType(
        type_name="Rocky",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=2,
        mutation_recipe=["Azure [Max]", "Azure [Max]", "Azure [Max]", "Azure [Max]"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Wooden": PlantType(
        type_name="Wooden",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=2,
        mutation_recipe=["Azure [Max]", "Azure [Max]", "Azure [Max]", "Azure [Max]"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Shadow": PlantType(
        type_name="Shadow",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=2,
        mutation_recipe=["Azure [Max]", "Azure [Max]", "Azure [Max]", "Azure [Max]"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Shining": PlantType(
        type_name="Shining",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=2,
        mutation_recipe=["Azure [Max]", "Azure [Max]", "Azure [Max]", "Azure [Max]"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Blizzard": PlantType(
        type_name="Blizzard",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=2,
        mutation_recipe=["Azure [Max]", "Azure [Max]", "Azure [Max]", "Azure [Max]"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Infernal": PlantType(
        type_name="Infernal",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=2,
        mutation_recipe=["Azure [Max]", "Azure [Max]", "Azure [Max]", "Azure [Max]"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Crystalline": PlantType(
        type_name="Crystalline",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=3,
        mutation_recipe=["Azure [Max]", "Azure [Max]", "Azure [Max]", "Azure [Max]"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Spectral": PlantType(
        type_name="Spectral",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=3,
        mutation_recipe=["Azure [Max]", "Azure [Max]", "Azure [Max]", "Azure [Max]"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Necrotic": PlantType(
        type_name="Necrotic",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=3,
        mutation_recipe=["Azure [Max]", "Azure [Max]", "Azure [Max]", "Azure [Max]"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Metallic": PlantType(
        type_name="Metallic",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=3,
        mutation_recipe=["Azure [Max]", "Azure [Max]", "Azure [Max]", "Azure [Max]"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Ivory": PlantType(
        type_name="Ivory",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=3,
        mutation_recipe=["Azure [Max]", "Azure [Max]", "Azure [Max]", "Azure [Max]"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Ebony": PlantType(
        type_name="Ebony",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=3,
        mutation_recipe=["Azure [Max]", "Azure [Max]", "Azure [Max]", "Azure [Max]"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Vital": PlantType(
        type_name="Vital",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=3,
        mutation_recipe=["Azure [Max]", "Azure [Max]", "Azure [Max]", "Azure [Max]"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Magmatic": PlantType(
        type_name="Magmatic",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=3,
        mutation_recipe=["Azure [Max]", "Azure [Max]", "Azure [Max]", "Azure [Max]"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Glacial": PlantType(
        type_name="Glacial",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=3,
        mutation_recipe=["Azure [Max]", "Azure [Max]", "Azure [Max]", "Azure [Max]"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Decaying": PlantType(
        type_name="Decaying",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=4,
        mutation_recipe=["Azure [Max]", "Azure [Max]", "Azure [Max]", "Azure [Max]"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Binary": PlantType(
        type_name="Binary",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=4,
        mutation_recipe=["Azure [Max]", "Azure [Max]", "Azure [Max]", "Azure [Max]"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Paradoxical": PlantType(
        type_name="Paradoxical",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=4,
        mutation_recipe=["Azure [Max]", "Azure [Max]", "Azure [Max]", "Azure [Max]"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Hasted": PlantType(
        type_name="Hasted",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=4,
        mutation_recipe=["Azure [Max]", "Azure [Max]", "Azure [Max]", "Azure [Max]"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Temporal": PlantType(
        type_name="Temporal",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=4,
        mutation_recipe=["Azure [Max]", "Azure [Max]", "Azure [Max]", "Azure [Max]"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Hollow": PlantType(
        type_name="Hollow",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=4,
        mutation_recipe=["Azure [Max]", "Azure [Max]", "Azure [Max]", "Azure [Max]"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Endothermic": PlantType(
        type_name="Endothermic",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=4,
        mutation_recipe=["Azure [Max]", "Azure [Max]", "Azure [Max]", "Azure [Max]"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Exothermic": PlantType(
        type_name="Exothermic",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=4,
        mutation_recipe=["Azure [Max]", "Azure [Max]", "Azure [Max]", "Azure [Max]"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Steel": PlantType(
        type_name="Steel",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=4,
        mutation_recipe=["Azure [Max]", "Azure [Max]", "Azure [Max]", "Azure [Max]"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Explosive": PlantType(
        type_name="Explosive",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=5,
        mutation_recipe=["Azure [Max]", "Azure [Max]", "Azure [Max]", "Azure [Max]"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Nocturnal": PlantType(
        type_name="Nocturnal",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=5,
        mutation_recipe=["Azure [Max]", "Azure [Max]", "Azure [Max]", "Azure [Max]"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Photonic": PlantType(
        type_name="Photonic",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=5,
        mutation_recipe=["Azure [Max]", "Azure [Max]", "Azure [Max]", "Azure [Max]"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Radioactive": PlantType(
        type_name="Radioactive",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=5,
        mutation_recipe=["Azure [Max]", "Azure [Max]", "Azure [Max]", "Azure [Max]"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Obscure": PlantType(
        type_name="Obscure",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=5,
        mutation_recipe=["Azure [Max]", "Azure [Max]", "Azure [Max]", "Azure [Max]"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Tungsten": PlantType(
        type_name="Tungsten",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=5,
        mutation_recipe=["Azure [Max]", "Azure [Max]", "Azure [Max]", "Azure [Max]"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Dull": PlantType(
        type_name="Dull",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=5,
        mutation_recipe=["Azure [Max]", "Azure [Max]", "Azure [Max]", "Azure [Max]"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Abyssal": PlantType(
        type_name="Abyssal",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=5,
        mutation_recipe=["Azure [Max]", "Azure [Max]", "Azure [Max]", "Azure [Max]"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Lunar": PlantType(
        type_name="Lunar",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=6,
        mutation_recipe=["Azure [Max]", "Azure [Max]", "Azure [Max]", "Azure [Max]"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Solar": PlantType(
        type_name="Solar",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=6,
        mutation_recipe=["Azure [Max]", "Azure [Max]", "Azure [Max]", "Azure [Max]"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Twilight": PlantType(
        type_name="Twilight",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=6,
        mutation_recipe=["Azure [Max]", "Azure [Max]", "Azure [Max]", "Azure [Max]"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Unstable": PlantType(
        type_name="Unstable",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=6,
        mutation_recipe=["Azure [Max]", "Azure [Max]", "Azure [Max]", "Azure [Max]"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Synthetic": PlantType(
        type_name="Synthetic",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=6,
        mutation_recipe=["Azure [Max]", "Azure [Max]", "Azure [Max]", "Azure [Max]"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Eternal": PlantType(
        type_name="Eternal",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=7,
        mutation_recipe=["Azure [Max]", "Azure [Max]", "Azure [Max]", "Azure [Max]"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Celestial": PlantType(
        type_name="Celestial",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=7,
        mutation_recipe=["Azure [Max]", "Azure [Max]", "Azure [Max]", "Azure [Max]"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Programmed": PlantType(
        type_name="Programmed",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=7,
        mutation_recipe=["Azure [Max]", "Azure [Max]", "Azure [Max]", "Azure [Max]"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),
    "Nuclear": PlantType(
        type_name="Nuclear",
        base_starting_age=[0, 0],
        base_adult_age=[300, 300],
        base_death_age=[480, 480],
        base_mutation_chance=1,
        base_yield=[150, 150],
        base_value=[100, 100],
        mult_adult_age=[1, 1],
        mult_death_age=[1, 1],
        mult_growth_speed=[1, 1],
        mult_yield=[1, 1],
        mult_value=[1, 1],
        ability_eff=[100, 100],
        resistance=0,
        resistance_cap=100,
        tier=7,
        mutation_recipe=["Azure [Max]", "Azure [Max]", "Azure [Max]", "Azure [Max]"],
        colour=GREEN,
        is_unlocked=False,
        primary_description=
        ["Stuff",
         " There",
         " Is",
         " Stuff",
         "----------------------------------------"],
        secondary_description=
        ["Stuff",
         " I",
         " Am",
         " Stuff",
         "----------------------------------------"]
    ),

}
